### ISSUE TITLE
I Can't convert interface extends.

### ISSUE THREAD

**Issue by HyeongHwanKim** [CauseXL/Interface-to-Object#1]
I Can't convert interface extends.

○ Example
interface A {
   a: string
}
interface B extends A {
   b: string
}

○ Run result
const c = {b: ''}

○ I hope
const c = {a: '', b: ''}

**Comment by CauseXL** [comment]
@HyeongHwanKim 

Add extends keyword support in [this PR](https://github.com/CauseXL/Interface-to-Object/pull/2)

- Checkout out the usage: https://github.com/CauseXL/Interface-to-Object#flaw
